/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_QAPI_COMMANDS_INJECTION_TRACE_EVENTS_GENERATED_TRACERS_H
#define TRACE_QAPI_COMMANDS_INJECTION_TRACE_EVENTS_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_QMP_ENTER_READMEM_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_READMEM_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_WRITEMEM_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_WRITEMEM_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_TRIGGEREVENT_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_TRIGGEREVENT_EVENT;
extern TraceEvent _TRACE_QMP_ENTER_INJECTGPIO_EVENT;
extern TraceEvent _TRACE_QMP_EXIT_INJECTGPIO_EVENT;
extern uint16_t _TRACE_QMP_ENTER_READMEM_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_READMEM_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_WRITEMEM_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_WRITEMEM_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_TRIGGEREVENT_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_TRIGGEREVENT_DSTATE;
extern uint16_t _TRACE_QMP_ENTER_INJECTGPIO_DSTATE;
extern uint16_t _TRACE_QMP_EXIT_INJECTGPIO_DSTATE;
#define TRACE_QMP_ENTER_READMEM_ENABLED 1
#define TRACE_QMP_EXIT_READMEM_ENABLED 1
#define TRACE_QMP_ENTER_WRITEMEM_ENABLED 1
#define TRACE_QMP_EXIT_WRITEMEM_ENABLED 1
#define TRACE_QMP_ENTER_TRIGGEREVENT_ENABLED 1
#define TRACE_QMP_EXIT_TRIGGEREVENT_ENABLED 1
#define TRACE_QMP_ENTER_INJECTGPIO_ENABLED 1
#define TRACE_QMP_EXIT_INJECTGPIO_ENABLED 1
#include "qemu/log-for-trace.h"
#include "qemu/error-report.h"


#define TRACE_QMP_ENTER_READMEM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_READMEM) || \
    false)

static inline void _nocheck__trace_qmp_enter_readmem(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_READMEM) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 3 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_readmem " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 52 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 3 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_enter_readmem " "%s" "\n", json);
#line 56 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_readmem(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_readmem(json);
    }
}

#define TRACE_QMP_EXIT_READMEM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_READMEM) || \
    false)

static inline void _nocheck__trace_qmp_exit_readmem(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_READMEM) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 4 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_readmem " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 83 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 4 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_exit_readmem " "%s %d" "\n", result, succeeded);
#line 87 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_readmem(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_readmem(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_WRITEMEM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_WRITEMEM) || \
    false)

static inline void _nocheck__trace_qmp_enter_writemem(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_WRITEMEM) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 5 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_writemem " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 114 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 5 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_enter_writemem " "%s" "\n", json);
#line 118 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_writemem(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_writemem(json);
    }
}

#define TRACE_QMP_EXIT_WRITEMEM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_WRITEMEM) || \
    false)

static inline void _nocheck__trace_qmp_exit_writemem(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_WRITEMEM) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 6 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_writemem " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 145 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 6 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_exit_writemem " "%s %d" "\n", result, succeeded);
#line 149 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_writemem(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_writemem(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_TRIGGEREVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_TRIGGEREVENT) || \
    false)

static inline void _nocheck__trace_qmp_enter_triggerevent(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_TRIGGEREVENT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 7 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_triggerevent " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 176 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 7 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_enter_triggerevent " "%s" "\n", json);
#line 180 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_triggerevent(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_triggerevent(json);
    }
}

#define TRACE_QMP_EXIT_TRIGGEREVENT_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_TRIGGEREVENT) || \
    false)

static inline void _nocheck__trace_qmp_exit_triggerevent(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_TRIGGEREVENT) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 8 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_triggerevent " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 207 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 8 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_exit_triggerevent " "%s %d" "\n", result, succeeded);
#line 211 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_triggerevent(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_triggerevent(result, succeeded);
    }
}

#define TRACE_QMP_ENTER_INJECTGPIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_ENTER_INJECTGPIO) || \
    false)

static inline void _nocheck__trace_qmp_enter_injectgpio(const char * json)
{
    if (trace_event_get_state(TRACE_QMP_ENTER_INJECTGPIO) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 9 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_enter_injectgpio " "%s" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , json);
#line 238 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 9 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_enter_injectgpio " "%s" "\n", json);
#line 242 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_enter_injectgpio(const char * json)
{
    if (true) {
        _nocheck__trace_qmp_enter_injectgpio(json);
    }
}

#define TRACE_QMP_EXIT_INJECTGPIO_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_QMP_EXIT_INJECTGPIO) || \
    false)

static inline void _nocheck__trace_qmp_exit_injectgpio(const char * result, bool succeeded)
{
    if (trace_event_get_state(TRACE_QMP_EXIT_INJECTGPIO) && qemu_loglevel_mask(LOG_TRACE)) {
        if (message_with_timestamp) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
#line 10 "qapi/qapi-commands-injection.trace-events"
            qemu_log("%d@%zu.%06zu:qmp_exit_injectgpio " "%s %d" "\n",
                     qemu_get_thread_id(),
                     (size_t)_now.tv_sec, (size_t)_now.tv_usec
                     , result, succeeded);
#line 269 "trace/trace-qapi_commands_injection_trace_events.h"
        } else {
#line 10 "qapi/qapi-commands-injection.trace-events"
            qemu_log("qmp_exit_injectgpio " "%s %d" "\n", result, succeeded);
#line 273 "trace/trace-qapi_commands_injection_trace_events.h"
        }
    }
}

static inline void trace_qmp_exit_injectgpio(const char * result, bool succeeded)
{
    if (true) {
        _nocheck__trace_qmp_exit_injectgpio(result, succeeded);
    }
}
#endif /* TRACE_QAPI_COMMANDS_INJECTION_TRACE_EVENTS_GENERATED_TRACERS_H */
