/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-qapi_commands_injection_trace_events.h"

uint16_t _TRACE_QMP_ENTER_READMEM_DSTATE;
uint16_t _TRACE_QMP_EXIT_READMEM_DSTATE;
uint16_t _TRACE_QMP_ENTER_WRITEMEM_DSTATE;
uint16_t _TRACE_QMP_EXIT_WRITEMEM_DSTATE;
uint16_t _TRACE_QMP_ENTER_TRIGGEREVENT_DSTATE;
uint16_t _TRACE_QMP_EXIT_TRIGGEREVENT_DSTATE;
uint16_t _TRACE_QMP_ENTER_INJECTGPIO_DSTATE;
uint16_t _TRACE_QMP_EXIT_INJECTGPIO_DSTATE;
TraceEvent _TRACE_QMP_ENTER_READMEM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_readmem",
    .sstate = TRACE_QMP_ENTER_READMEM_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_READMEM_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_READMEM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_readmem",
    .sstate = TRACE_QMP_EXIT_READMEM_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_READMEM_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_WRITEMEM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_writemem",
    .sstate = TRACE_QMP_ENTER_WRITEMEM_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_WRITEMEM_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_WRITEMEM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_writemem",
    .sstate = TRACE_QMP_EXIT_WRITEMEM_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_WRITEMEM_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_TRIGGEREVENT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_triggerevent",
    .sstate = TRACE_QMP_ENTER_TRIGGEREVENT_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_TRIGGEREVENT_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_TRIGGEREVENT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_triggerevent",
    .sstate = TRACE_QMP_EXIT_TRIGGEREVENT_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_TRIGGEREVENT_DSTATE 
};
TraceEvent _TRACE_QMP_ENTER_INJECTGPIO_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_enter_injectgpio",
    .sstate = TRACE_QMP_ENTER_INJECTGPIO_ENABLED,
    .dstate = &_TRACE_QMP_ENTER_INJECTGPIO_DSTATE 
};
TraceEvent _TRACE_QMP_EXIT_INJECTGPIO_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_exit_injectgpio",
    .sstate = TRACE_QMP_EXIT_INJECTGPIO_ENABLED,
    .dstate = &_TRACE_QMP_EXIT_INJECTGPIO_DSTATE 
};
TraceEvent *qapi_commands_injection_trace_events_trace_events[] = {
    &_TRACE_QMP_ENTER_READMEM_EVENT,
    &_TRACE_QMP_EXIT_READMEM_EVENT,
    &_TRACE_QMP_ENTER_WRITEMEM_EVENT,
    &_TRACE_QMP_EXIT_WRITEMEM_EVENT,
    &_TRACE_QMP_ENTER_TRIGGEREVENT_EVENT,
    &_TRACE_QMP_EXIT_TRIGGEREVENT_EVENT,
    &_TRACE_QMP_ENTER_INJECTGPIO_EVENT,
    &_TRACE_QMP_EXIT_INJECTGPIO_EVENT,
  NULL,
};

static void trace_qapi_commands_injection_trace_events_register_events(void)
{
    trace_event_register_group(qapi_commands_injection_trace_events_trace_events);
}
trace_init(trace_qapi_commands_injection_trace_events_register_events)
