/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-hw_watchdog.h"

uint16_t _TRACE_CMSDK_APB_WATCHDOG_READ_DSTATE;
uint16_t _TRACE_CMSDK_APB_WATCHDOG_WRITE_DSTATE;
uint16_t _TRACE_CMSDK_APB_WATCHDOG_RESET_DSTATE;
uint16_t _TRACE_CMSDK_APB_WATCHDOG_LOCK_DSTATE;
uint16_t _TRACE_ASPEED_WDT_READ_DSTATE;
uint16_t _TRACE_ASPEED_WDT_WRITE_DSTATE;
uint16_t _TRACE_SPAPR_WATCHDOG_START_DSTATE;
uint16_t _TRACE_SPAPR_WATCHDOG_STOP_DSTATE;
uint16_t _TRACE_SPAPR_WATCHDOG_QUERY_DSTATE;
uint16_t _TRACE_SPAPR_WATCHDOG_QUERY_LPM_DSTATE;
uint16_t _TRACE_SPAPR_WATCHDOG_EXPIRED_DSTATE;
TraceEvent _TRACE_CMSDK_APB_WATCHDOG_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "cmsdk_apb_watchdog_read",
    .sstate = TRACE_CMSDK_APB_WATCHDOG_READ_ENABLED,
    .dstate = &_TRACE_CMSDK_APB_WATCHDOG_READ_DSTATE 
};
TraceEvent _TRACE_CMSDK_APB_WATCHDOG_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "cmsdk_apb_watchdog_write",
    .sstate = TRACE_CMSDK_APB_WATCHDOG_WRITE_ENABLED,
    .dstate = &_TRACE_CMSDK_APB_WATCHDOG_WRITE_DSTATE 
};
TraceEvent _TRACE_CMSDK_APB_WATCHDOG_RESET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "cmsdk_apb_watchdog_reset",
    .sstate = TRACE_CMSDK_APB_WATCHDOG_RESET_ENABLED,
    .dstate = &_TRACE_CMSDK_APB_WATCHDOG_RESET_DSTATE 
};
TraceEvent _TRACE_CMSDK_APB_WATCHDOG_LOCK_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "cmsdk_apb_watchdog_lock",
    .sstate = TRACE_CMSDK_APB_WATCHDOG_LOCK_ENABLED,
    .dstate = &_TRACE_CMSDK_APB_WATCHDOG_LOCK_DSTATE 
};
TraceEvent _TRACE_ASPEED_WDT_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "aspeed_wdt_read",
    .sstate = TRACE_ASPEED_WDT_READ_ENABLED,
    .dstate = &_TRACE_ASPEED_WDT_READ_DSTATE 
};
TraceEvent _TRACE_ASPEED_WDT_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "aspeed_wdt_write",
    .sstate = TRACE_ASPEED_WDT_WRITE_ENABLED,
    .dstate = &_TRACE_ASPEED_WDT_WRITE_DSTATE 
};
TraceEvent _TRACE_SPAPR_WATCHDOG_START_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "spapr_watchdog_start",
    .sstate = TRACE_SPAPR_WATCHDOG_START_ENABLED,
    .dstate = &_TRACE_SPAPR_WATCHDOG_START_DSTATE 
};
TraceEvent _TRACE_SPAPR_WATCHDOG_STOP_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "spapr_watchdog_stop",
    .sstate = TRACE_SPAPR_WATCHDOG_STOP_ENABLED,
    .dstate = &_TRACE_SPAPR_WATCHDOG_STOP_DSTATE 
};
TraceEvent _TRACE_SPAPR_WATCHDOG_QUERY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "spapr_watchdog_query",
    .sstate = TRACE_SPAPR_WATCHDOG_QUERY_ENABLED,
    .dstate = &_TRACE_SPAPR_WATCHDOG_QUERY_DSTATE 
};
TraceEvent _TRACE_SPAPR_WATCHDOG_QUERY_LPM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "spapr_watchdog_query_lpm",
    .sstate = TRACE_SPAPR_WATCHDOG_QUERY_LPM_ENABLED,
    .dstate = &_TRACE_SPAPR_WATCHDOG_QUERY_LPM_DSTATE 
};
TraceEvent _TRACE_SPAPR_WATCHDOG_EXPIRED_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "spapr_watchdog_expired",
    .sstate = TRACE_SPAPR_WATCHDOG_EXPIRED_ENABLED,
    .dstate = &_TRACE_SPAPR_WATCHDOG_EXPIRED_DSTATE 
};
TraceEvent *hw_watchdog_trace_events[] = {
    &_TRACE_CMSDK_APB_WATCHDOG_READ_EVENT,
    &_TRACE_CMSDK_APB_WATCHDOG_WRITE_EVENT,
    &_TRACE_CMSDK_APB_WATCHDOG_RESET_EVENT,
    &_TRACE_CMSDK_APB_WATCHDOG_LOCK_EVENT,
    &_TRACE_ASPEED_WDT_READ_EVENT,
    &_TRACE_ASPEED_WDT_WRITE_EVENT,
    &_TRACE_SPAPR_WATCHDOG_START_EVENT,
    &_TRACE_SPAPR_WATCHDOG_STOP_EVENT,
    &_TRACE_SPAPR_WATCHDOG_QUERY_EVENT,
    &_TRACE_SPAPR_WATCHDOG_QUERY_LPM_EVENT,
    &_TRACE_SPAPR_WATCHDOG_EXPIRED_EVENT,
  NULL,
};

static void trace_hw_watchdog_register_events(void)
{
    trace_event_register_group(hw_watchdog_trace_events);
}
trace_init(trace_hw_watchdog_register_events)
